# -*- coding: utf-8 -*-
"""energy-consumption-ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzXcCs-m02YPEnQkDUKWnDChs8jBpR_0

AI Energy Consumption Forecasting & Optimization System

Features:
- Time-series energy prediction using ML
- Lag-based feature engineering
- Smart usage recommendation system
- Future consumption prediction
- Trend analysis visualization

Tech Stack:
Python, Pandas, Scikit-learn, Matplotlib
"""

# =========================
# ALL-IN-ONE ENERGY AI PROJECT
# =========================

# Upload zip file
from google.colab import files
uploaded = files.upload()

# Unzip
import zipfile, os

zip_name = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall()

print("Files after unzip:", os.listdir())

# =========================
# IMPORT LIBRARIES
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# =========================
# LOAD DATA (AUTO DETECT FILE)
# =========================
file_name = None
for file in os.listdir():
    if file.endswith(".csv"):
        file_name = file

df = pd.read_csv(file_name)
print("Loaded file:", file_name)

# =========================
# DATETIME CREATION
# =========================
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], dayfirst=True)
df.set_index('Datetime', inplace=True)

# =========================
# CLEAN DATA
# =========================
df = df[['Global_active_power']]
df['Global_active_power'] = pd.to_numeric(df['Global_active_power'], errors='coerce')
df.dropna(inplace=True)

# =========================
# RESAMPLE
# =========================
df_hourly = df.resample('H').mean()

# =========================
# FEATURE ENGINEERING
# =========================
df_hourly['hour'] = df_hourly.index.hour
df_hourly['day'] = df_hourly.index.day
df_hourly['month'] = df_hourly.index.month
df_hourly['day_of_week'] = df_hourly.index.dayofweek
df_hourly['is_weekend'] = df_hourly['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

df_hourly['prev_hour'] = df_hourly['Global_active_power'].shift(1)
df_hourly['prev_day'] = df_hourly['Global_active_power'].shift(24)

df_hourly.dropna(inplace=True)

# =========================
# MODEL TRAINING
# =========================
X = df_hourly[['hour','day','month','day_of_week','is_weekend','prev_hour','prev_day']]
y = df_hourly['Global_active_power']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = GradientBoostingRegressor()
model.fit(X_train, y_train)

pred = model.predict(X_test)

# =========================
# EVALUATION
# =========================
print("\n📊 MODEL PERFORMANCE")
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

# =========================
# VISUALIZATION
# =========================
plt.figure(figsize=(12,6))
plt.plot(y_test.values[:200], label='Actual')
plt.plot(pred[:200], label='Predicted')
plt.legend()
plt.title("Energy Consumption Prediction")
plt.show()

# =========================
# SMART INSIGHT
# =========================
def smart_suggestion(power):
    avg = df_hourly['Global_active_power'].mean()
    if power > avg * 1.3:
        return "🚨 High Usage"
    elif power > avg:
        return "⚠️ Moderate Usage"
    else:
        return "✅ Normal Usage"

print("\n💡 Sample Insight:", smart_suggestion(pred[0]))

# =========================
# FUTURE PREDICTION
# =========================
last_row = df_hourly.iloc[-1]

future_input = pd.DataFrame({
    'hour':[last_row.name.hour],
    'day':[last_row.name.day],
    'month':[last_row.name.month],
    'day_of_week':[last_row.name.dayofweek],
    'is_weekend':[1 if last_row.name.dayofweek>=5 else 0],
    'prev_hour':[last_row['Global_active_power']],
    'prev_day':[df_hourly.iloc[-24]['Global_active_power']]
})

future_pred = model.predict(future_input)

print("\n🔮 Next Hour Prediction:", future_pred[0])
print("💡 Suggestion:", smart_suggestion(future_pred[0]))

# =========================
# TREND ANALYSIS
# =========================
df_hourly['Global_active_power'].resample('D').mean().plot(figsize=(10,5))
plt.title("Daily Energy Consumption Trend")
plt.show()

file_name = None
for file in os.listdir():
    if file.endswith(".csv"):
        file_name = file

if file_name is None:
    raise Exception("❌ No CSV file found in zip")

df = pd.read_csv(file_name)
print("Loaded file:", file_name)